### ISSUE TITLE
(8) Share modal for Works

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#128]
### Descriptive Summary:

As a user, when I click the 'Share' Button on a work's page, I am taken the a modal that has the following information and links:
- Twitter icon link 
- Facebook icon link
- Email icon link (what email service should this connect to?) 
- Permalink
- Embeded Code
- Size (what are the different size options in the drop down 

### Mock Ups:

**Example of Share button with share icon:**
![Screen Shot 2019-11-20 at 3 49 36 PM](https://user-images.githubusercontent.com/9621070/69291581-85820480-0bb8-11ea-87f2-df76986841c5.png)

**Example of Share Modal:**
![Screen Shot 2019-11-20 at 5 08 53 PM](https://user-images.githubusercontent.com/9621070/69291556-78fdac00-0bb8-11ea-9d90-6ecfab43c663.png)

### Acceptance Criteria:

* [x] Twitter icon link allows user to post to their Twitter account 
* [x] Facebook icon link allows user to post to their facebook account 
* [x] Email icon link allows user to send email (do we need to determine what email service?)
* [ ] Embeded Code will contain a block of HTML, which is embedded in the page-source for the IIIF Viewer - Ryan speak to Jess about this 
* [x] Drop down with the following size options for the IIF embeded code 

### Notes 

May need to break this story down further. This ticket is loosely related to #94 Ability to click through child works from parent work page.

**Comment by JessWaggs** [comment]
The embed options I just pulled from what we currently have via the Universal Viewer. It allows the user to specify a size for the embedded image.

**Comment by rschwab** [comment]
What should happen with the email button? If we use a mailto: link it will open the users default mail client, but not be useable by web-based email. Another option is to have a popover menu with multiple links, like Zoom has in their invite by email screen. We can construct links for Gmail and Yahoo mail at least, there may be others that support it too.

Beyond that, what should be the default email subject and body when these links open?

**Comment by rschwab** [comment]
Here's the way Zoom handles this:
![email-options](https://user-images.githubusercontent.com/515412/76572631-da070380-6477-11ea-893f-78337afc41eb.png)

**Comment by JessWaggs** [comment]
@rschwab Good question! Would it be possible to have the modal display change to something like this after the user selects "Email" from the initial modal?

![Screen Shot 2020-03-12 at 3 56 09 PM](https://user-images.githubusercontent.com/6412857/76574676-3539f580-647a-11ea-8432-2f7d8271415d.png)

**Comment by rschwab** [comment]
@JessWaggs Yeah I think that's possible. Does this mean the server is sending the email instead of being a link to the users email?

**Comment by rschwab** [comment]
Some notes about the embed code if we utilize what is present in UV:
- It is embed code for a universal viewer with the work pre-loaded.
- The embed code relies on javascript hosted on the DAMS server.
- That's good for tracking embeds around the net
- That's potentially bad for server load, depending on the extent of its usage.

**Comment by JessWaggs** [comment]
Yeah, I was picturing an option for the user to send themselves the permalink via email.

**Comment by rschwab** [comment]
@NedHenry Is the server set up to send email?

We should probably consider the potential for abuse, since this would be a way to send emails to arbitrary addresses over the web. Is a reCAPTCHA on this form acceptable? Having this function be a link to create an email in the users system would avoid these issues. I'm biased towards that option - because its more secure (but maybe because also I'm being lazy and its simpler hehe).

**Comment by JessWaggs** [comment]
I would tend toward simplicity on the user end : )   But if we need to consider security, I would think reCAPTCHA would be acceptable. 

I like the Primo interface for email as well:

![Screen Shot 2020-03-13 at 1 30 08 PM](https://user-images.githubusercontent.com/6412857/76657402-092c7c00-652f-11ea-949c-33bc86718184.png)

**Comment by rschwab** [comment]
@JessWaggs Its a lot less likely to be abused if we remove the comments box, which is where spam could get added. How do you feel about a primo-like experience where the user just enters an address to send it to?

**Comment by JessWaggs** [comment]
@rschwab  Sounds perfect! Let's follow the primo style on it : )

**Comment by JessWaggs** [comment]
(Though if the the Subject could be the name of the actual object rather than something generic - that would be awesome!)

**Comment by rschwab** [comment]
@JessWaggs How important is it that the Universal Viewer be utilized in the embed code? Is that a requirement, or a design shortcut? I'm asking because I'm finding it extremely difficult to untangle and replicate the embed code in UV to place it in our modal window. If its not important, I can pivot to a simpler method.

**Comment by JessWaggs** [comment]
@rschwab I was just using the embed code provided by the Universal Viewer as a shortcut. So if it's not a shortcut, definitely feel free to use whatever method for generating embed codes : )

**Comment by rschwab** [comment]
[Pull Request here](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/117)

Screenshots:
![Firefox_Screenshot_2020-04-07T18-40-10 917Z](https://user-images.githubusercontent.com/515412/78707391-66fd7b00-78c5-11ea-8c4e-498cdc75a63d.png)
![Firefox_Screenshot_2020-04-07T18-40-21 848Z](https://user-images.githubusercontent.com/515412/78707399-68c73e80-78c5-11ea-9b1b-833f946c2690.png)
![Firefox_Screenshot_2020-04-07T18-40-32 917Z](https://user-images.githubusercontent.com/515412/78707408-6b299880-78c5-11ea-9258-2bb8eca1f2b6.png)
![Firefox_Screenshot_2020-04-07T18-41-14 752Z](https://user-images.githubusercontent.com/515412/78707419-6d8bf280-78c5-11ea-936e-2dc13eff169c.png)
Attempt to re-create the HTML email in the browser (code snippets will be replace with actual page title and permanent link):
![Firefox_Screenshot_2020-04-07T18-44-25 630Z](https://user-images.githubusercontent.com/515412/78707489-87c5d080-78c5-11ea-9f7f-6cabe266699d.png)

**Comment by rschwab** [comment]
Requires [Enable flash messages](https://github.com/UCSCLibrary/dams_project_mgmt/issues/258)
Requires [Enable ActionMailer](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/362)

**Comment by chesleyperry** [comment]
Email issues:  The system prompted me to login to the staging server before I could send an email from the modal.  Once I did, it worked! 
Embed issues:  When I embedded an image into a Drupal page, it gives me a plain black box instead of the image.  I'm not sure if the problem is partially caused by the fact I'm on the staging server or if there's another issue.  Let me know if I should try embedding it into another CMS.

**Comment by NedHenry** [comment]
Thanks Sue! I believe that I have resolved these two issues. 
The emails should work now, whether you are logged in or not.
There was a small issue with the embed codes that were issued. To fix the problem, either change "http" to "https" in the existing embed codes in Drupal, or just copy and paste the codes again from the staging site (which now displays the correct codes).

**Comment by chesleyperry** [comment]
Hi @NedHenry ,
The embed code is still not working but the email is successful (yay!)
For the embedded images, I just get a black box with a turning square in the middle of it, but the image doesn't load.  I tried in LibGuides and Drupal with the same result.
See the screenshot:
<img width="581" alt="Screen Shot 2020-05-27 at 2 52 36 PM" src="https://user-images.githubusercontent.com/18403313/83076509-8ba2e300-a02a-11ea-9fe9-f9e2323e8c43.png">

**Comment by NedHenry** [comment]
Hi Sue, do you mind sharing an example URL of a page where you are seeing this error?
Many thanks!
Ned

**Comment by chesleyperry** [comment]
@NedHenry:  It's working now!  Maybe because I wasn't connected to the VPN before?
Here are the two pages:
LibGuides - https://guides.library.ucsc.edu/test-embed
Drupal - https://library.ucsc.edu/test-dams-embed
